name: check-awesome-links

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Checks
      run: |
        gem install awesome_bot
        awesome_bot --white-list example.com,github.com,creativecommons.org,www.amara.com,explore-group.com,www.sainsburys.co.uk --set-timeout 5 --allow-timeout *.md
